#!/usr/bin/env php
<?php

require __DIR__ . '/app/helpers.php';
require __DIR__ . '/vendor/autoload.php';

use App\Console\Commands\DeployPruneCommand;
use App\Console\Commands\DeployRepoCommand;
use App\DeployManager;
use App\Github;
use Symfony\Component\Console\Application;

$application = new Application('PaulboCo', '1.0');

$application->add(new DeployRepoCommand(new Github, new DeployManager));
$application->add(new DeployPruneCommand(new DeployManager));

$application->run();
