#!/usr/bin/env php
<?php


date_default_timezone_set('America/Chicago');
$base_dir = __DIR__;
$option = isset($argv[1]) ? $argv[1] : null;

#--------------------------------------------------------------------------
# Configuration
#--------------------------------------------------------------------------

$repo = 'https://github.com/paulboco/peon.git';
$release_dir = $base_dir . '/releases/';
$deploy_dir = $base_dir . '/current/';
$release = $option ? $release = 'release_20151112171824' : 'release_' . date('YmdHis');

$env = <<<EOD
<?php

putenv('DB_DSN=mysql:host=localhost;dbname=peon');
putenv('DB_USER=root');
putenv('DB_PASS=root');

EOD;

chdir($base_dir);
if ($option != 'test') {
    exec("git clone --depth 1 {$repo} {$release_dir}{$release}");
}
chdir($release_dir . $release);
file_put_contents('.env', $env);
exec("php clid seed");
exec("ln -sfn {$release_dir}{$release}/public {$deploy_dir}");