#!/usr/bin/env php
<?php

date_default_timezone_set('America/Chicago');
$base_dir = __DIR__;

#--------------------------------------------------------------------------
# Configuration
#--------------------------------------------------------------------------

$repo = 'git@github.com:paulboco/peon.git';
$release_dir = $base_dir . '/releases/';
$deploy_dir = $base_dir . '/current/';
$release = 'release_' . date('YmdHis');
$release = 'release_20151112143206';

$env = <<<EOD
<?php

putenv('DB_DSN=mysql:host=localhost;dbname=peon');
putenv('DB_USER=root');
putenv('DB_PASS=root');

EOD;

chdir($base_dir);
// exec("git clone --depth 1 {$repo} {$release_dir}{$release}");
chdir($release_dir . $release);
file_put_contents('.env', $env);
// exec("php clid seed");
exec("ln -sfn {$release_dir}{$release}/public {$deploy_dir}");